config/routes.rb
SWorD::Application.routes.draw do
  root :to => 'pages#home'

  match '/cerca', to: 'pages#cerca'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers, :amici, :gallery, :messaggi, :il_mio_birrificio, :in_cantina, :gusta,
            :mercatino, :gruppi, :dettaglio_incantina, :dettaglio_incantina2, :dettaglio_gusta, :dettaglio_gusta2,
             :voto # ex.: get /users/1/followers
    end
    collection do
      get :search, :search_tag
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

end

app/views/shared/_barra_amico.html.erb
<% if @user != current_user %>
    <div id="barramenu_amico">

      <nav id="iconeamico">
        <ul>

          <li><%= link_to image_tag("Icon/ProfiloIcon.png", :size => "50x50"),  { :action => "show", :controller => "users" } %>   </li>
          <li><%= link_to image_tag("Icon/AmiciIcon.png", :size => "60x60"), { :action => "amici", :controller => "users" }%> </li>
          <li><%= link_to image_tag("Icon/GalleryIcon.png", :size => "50x50"),{ :action => "gallery", :controller => "users" }%> </li>
          <li><%= link_to image_tag("Icon/MessaggiIcon.png", :size => "60x60"), { :action => "messaggi", :controller => "users" }%> </li>
          <% if @user.chisei == 'Mastro Birraio' %>
          <li><%= link_to image_tag("Icon/BirrificioIcon.png", :size => "50x50"), { :action => "il_mio_birrificio", :controller => "users" }%> </li>
          <% end %>
          <% if @user.chisei != 'Appassionato di birra' %>
          <li><%= link_to image_tag("Icon/InCantinaIcon.png", :size => "60x60"), { :action => "in_cantina", :controller => "users" }%> </li>
          <% end %>
          <li><%= link_to image_tag("Icon/GustaIcon.png", :size =>"40x40"), { :action => "gusta", :controller => "users" } %> </li>
          <li><%= link_to image_tag("Icon/MercatinoIcon.png", :size => "60x60"), { :action => "mercatino", :controller => "users" }%> </li>
          <li><%= link_to image_tag("Icon/GruppiIcon.png", :size => "40x40"), { :action => "gruppi", :controller => "users" }%> </li>

        </ul>
      </nav>

    </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% # handle and show forms errors %>
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, 'error') %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |message| %>
            <li>* <%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <% # we need to write in this way the partial rendering for passing the collection %>
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago
  </span>
</li>

app/views/shared/_infoutente.erb
<div id="nomeutente">
  <h3> <%= @user.name %> </h3>
</div>

<div id="infoutente">
  <h3 id="infoutente"> - <%= @user.chisei %> -  </h3>
</div>

  <nav id="tagutente">
  <ul>
   <li>
     <% if !@user.tag1.blank? %>
        <%= link_to @user.tag1, { :controller => "users", :action => "search_tag", :search_tag => @user.tag1}  %>
    <% end %>
     </li>
    <li><% if !@user.tag2.blank? %>
        <%= link_to @user.tag2, { :controller => "users", :action => "search_tag", :search_tag => @user.tag2} %>
    <% end %></li>
    <li><% if !@user.tag3.blank? %>
        <%= link_to @user.tag3, { :controller => "users", :action => "search_tag", :search_tag => @user.tag3} %>
    <% end %></li>
  </ul>
  </nav>


<div id="punteggioutente">
  <h2 id="punteggioutente"> <%= @user.punteggio.to_i %> Punti  </h2>
   </div>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="row">
    <div class="field span7">
      <%= f.text_area :content, placeholder: 'What are you doing?' %>
    </div>
    <div class="span2">
      <%= f.submit 'Post', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% # we are going to use this partial in the home and in the user profile;
   # in the home @user is nil and needs to be filled %>
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
     following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
     followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<% # current user gravatar %>
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>

<h1><%= current_user.name %></h1>
<span><%= pluralize(current_user.posts.count, 'post') %></span>