config/routes.rb
SWorD::Application.routes.draw do
  root :to => 'pages#home'

  match '/cerca', to: 'pages#cerca'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers, :amici, :gallery, :messaggi, :il_mio_birrificio, :in_cantina, :gusta,
            :mercatino, :gruppi, :dettaglio_incantina, :dettaglio_incantina2, :dettaglio_gusta, :dettaglio_gusta2,
             :voto # ex.: get /users/1/followers
    end
    collection do
      get :search, :search_tag
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

end

app/views/pages/about.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'About' %>

<h1>About</h1>
<p>A TuttaBirra è un Social Network dedicato alle varie tipologie di birra e dei metodi di produzione.
  Utile per ottenere consigli e per trovare le materie prime migliori per produrre la birra in casa.
  Gestione di compravendita tra appassionati.
  Elenco di tutte le tipologie di birra e metodi di produzione.</p>

app/views/pages/cerca.html.erb
<% provide :title, 'Cerca' %>

<h1 id="arancione">Cerca</h1>

<fieldset>
<div id="ricerca">
    <p id="ricerca">Ricerca tramite:</p>

    <%= form_tag search_users_path, method: 'get' do %>
        <%= render 'users/search_form' %>
    <% end %>


<div id="ricercagruppi">
<p id="ricercagruppi">
    <%= label_tag :gruppi %>
</p>
<p id="ricercagruppi">
    <%= text_field_tag :search, params[:search], class: 'search-query', placeholder: 'Search'  %>
</p>
<p id="ricercagruppi">
    <%= submit_tag "Search", disabled: true, class: 'btn btn-large btn-primary' %>
</p>
</div>


<%= form_tag search_tag_users_path, method: 'get' do %>
    <%= render 'users/search_form_tag' %>
<% end %>
</div>

</fieldset>

app/views/pages/contact.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Contact' %>

<h1>Contatti</h1>
<p>Luigi De Russis (<a href="mailto:luigi.derussis@polito.it?subject=ATuttaBirra">luigi.derussis@polito.it</a>)</p>
<p>Noemi Bodino (<a href="mailto:baudi90@libero.it?subject=ATuttaBirra">baudi90@libero.it</a>)</p>
<p>Michela Pratola (<a href="mailto:michela.pratola@gmail.com?subject=ATuttaBirra">michela.pratola@gmail.com</a>)</p>

app/views/pages/home.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Home' %>

<% if signed_in? %>

<div class="row">
<aside class="span3">
  <section>
    <%= render 'shared/user_info' %>
  </section>
  <section>
    <%= render 'shared/stats' %>
  </section>
</aside>
<div class="span9">
  <%= render 'shared/post_form' %>
  <h3>Diario Utente</h3>
  <%= render 'shared/feed' %>
</div>
</div>

<% else %>
<body id="home">
<div class="center hero-unit" id="classhome" >

<h1>Benvenuti su <br> A TuttaBirra!</h1>
<br>
<h2>
  Registrati o fai il LogIn  <br> per accedere ad A TuttaBirra
</h2>

<%= link_to 'Registrati!', signup_path, class: 'btn btn-large btn-primary' %>
</div>
</body>
<% end %>