config/routes.rb
SWorD::Application.routes.draw do
  root :to => 'pages#home'

  match '/cerca', to: 'pages#cerca'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers, :amici, :gallery, :messaggi, :il_mio_birrificio, :in_cantina, :gusta,
            :mercatino, :gruppi, :dettaglio_incantina, :dettaglio_incantina2, :dettaglio_gusta, :dettaglio_gusta2,
             :voto # ex.: get /users/1/followers
    end
    collection do
      get :search, :search_tag
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <%=link_to "A TuttaBirra",  root_path %>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
<div class="container">


  <nav id="navheader">
    <%=link_to image_tag("logo.png", :size => "100x100"), root_path %>
    <ul class="nav pull-right">
      <% #link_to is the Rails helper to create links (it generates <a...> tags) %>


      <% if signed_in? %>
            <li id="account"><a href="#" onClick="mostraAccount_menu();" > Account </a>

          </li>
      <% end %>

      <li><%=link_to "Home",    root_path %></li>

      <% if signed_in? %>

          <li><%= link_to "Cerca", cerca_path %></li>
          </li>

        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Impostazioni <b class="caret"></b></a>
          <ul class="dropdown-menu">

            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          </ul>
      <% else %>
        <li><%=link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</div>
</div>
</header>
<% if signed_in? %>
<div id="barramenu"style="display: none">

<nav id="icone">
<ul>

  <li><%= link_to image_tag("Icon/ProfiloIcon.png", :size => "70x70"), current_user %>   </li>
   <li><%= link_to image_tag("Icon/AmiciIcon.png", :size => "70x70"), { :action => "amici", :controller => "users", :id => current_user }%> </li>
  <li><%= link_to image_tag("Icon/GalleryIcon.png", :size => "70x70"),{ :action => "gallery", :controller => "users", :id => current_user }%> </li>
  <li><%= link_to image_tag("Icon/MessaggiIcon.png", :size => "80x80"), { :action => "messaggi", :controller => "users", :id => current_user }%> </li>
  <% if current_user.chisei == 'Mastro Birraio' %>
  <li><%= link_to image_tag("Icon/BirrificioIcon.png", :size => "70x70"), { :action => "il_mio_birrificio", :controller => "users", :id => current_user }%> </li>
  <% end %>
  <% if current_user.chisei != 'Appassionato di birra' %>
      <li><%= link_to image_tag("Icon/InCantinaIcon.png", :size => "90x90"), { :action => "in_cantina", :controller => "users", :id => current_user }%> </li>
  <% end %>
  <li><%= link_to image_tag("Icon/GustaIcon.png", :size =>"60x60"), { :action => "gusta", :controller => "users", :id => current_user } %> </li>
  <li><%= link_to image_tag("Icon/MercatinoIcon.png", :size => "80x80"), { :action => "mercatino", :controller => "users", :id => current_user }%> </li>
  <li><%= link_to image_tag("Icon/GruppiIcon.png", :size => "60x60"), { :action => "gruppi", :controller => "users", :id => current_user }%> </li>
  <li><a href="#" onClick="mostraAccount_menu();" > X </a></li>
</ul>
</nav>

</div><% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
<script src="http://htmlshim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <% # method to automatically prevent Cross-Site Request Forgery %>

  <%= csrf_meta_tags %>
  <% # partial for the HTML shim %>
  <%= render 'layouts/shim'%>
</head>
<body>
  <% # partial for the header %>
  <%= render 'layouts/header' %>

  <div class="container">
    <% # the flash message; it supports different type of communications %>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>

    <% # partial for the footer %>
    <%= render 'layouts/footer' %>


  </div>

</body>
</html>